name: Build and Test

on:
  push:
    branches: [gpu-codegen]
  pull_request:
    branches: [gpu-codegen]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Configure, build and check
    runs-on: self-hosted

    steps:
      # Clone the repo. Do shallow clone to save clone time.
      - name: Get LLVM (llvm-project private repo of MCL)
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Create build environment
        # Create a separate build directory. We'll use this as our working
        # directory for all subsequent commands.
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure build using CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS="mlir" -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_LLD=ON -DBUILD_SHARED_LIBS=ON -DMLIR_CUDA_RUNNER_ENABLED=ON -DLLVM_CCACHE_BUILD=ON -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc

      - name: Build & Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ninja check-mlir

        # This clang-format part of the script has been adapted from the CIRCT
        # project's action file: https://github.com/llvm/circt

        # Choose the git commit to diff against for the purposes of clang-format.
        # Since this workflow is triggered on both pushes and pull requests, we
        # have to determine if the pull request target branch is set (which it
        # will only be on the PR triggered flow). If it's not, then compare
        # against the last commit.
      - name: choose-commit
        if: ${{ always() }}
        env:
          # Base ref is the target branch, in text form (not hash)
          PR_BASE: ${{ github.base_ref }}
        run: |
          # Determine diff commit name.
          if [[ -z "$PR_BASE" ]]; then
            DIFF_COMMIT_NAME="HEAD^"
          else
            DIFF_COMMIT_NAME="$PR_BASE"
          fi
          echo "DIFF_COMMIT_NAME=$DIFF_COMMIT_NAME" >> $GITHUB_ENV

      # Since we did a shallow fetch for this repo, we must fetch the commit
      # upon which we be diff'ing. The last step set the ref name in the
      # $DIFF_COMMIT_NAME environment variable. When running the fetch, resolve
      # it to the commit hash and pass that hash along to subsequent steps.
      - name: git fetch base commit
        continue-on-error: true
        run: |
          if [[ ! "$DIFF_COMMIT_NAME" == *"HEAD"* ]]; then
            git fetch --recurse-submodules=no origin $DIFF_COMMIT_NAME
            DIFF_COMMIT_SHA=$( git rev-parse origin/$DIFF_COMMIT_NAME )
          else
            DIFF_COMMIT_SHA=$( git rev-parse $DIFF_COMMIT_NAME )
          fi
          echo "DIFF_COMMIT=$DIFF_COMMIT_SHA" >> $GITHUB_ENV

      # Run 'git clang-format', comparing against the target commit hash. If
      # clang-format fixed anything, fail and output a patch.
      - name: clang-format
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          # Run clang-format
          git clang-format $DIFF_COMMIT
          git diff --ignore-submodules > clang-format.patch
          if [ -s clang-format.patch ]; then
            echo "Clang-format found formatting problems in the following " \
              "files. See diff in the clang-format.patch artifact."
            git diff --ignore-submodules --name-only
            git checkout .
            exit 1
          fi
          echo "Clang-format found no formatting problems"
          exit 0

      # Upload the format patch to an artifact (zip'd) associated
      # with the workflow run. Only run this on a failure.
      - name: Upload format patch
        uses: actions/upload-artifact@v2
        continue-on-error: true
        if: ${{ failure() }}
        with:
          name: clang-format-patch
          path: clang-format.patch

               echo "DIFF_COMMIT_NAME=$DIFF_COMMIT_NAME" >> $GITHUB_ENV
